# timeout
timeout = "1200s"
# your website url
baseURL = 'https://peter-wyss.ch' # <-- MODIFY ME
# website title
title = 'Peter Wyss' # <-- MODIFY ME
# don't touch this
disableKinds = ["section", "taxonomy", "term", "home"]
# robots.txt
enableRobotsTXT = true
[module]
[[module.imports]]
path = "github.com/Sped0n/bridget/v2"