# timeout
timeout = "1200s"
# your website url
baseURL = 'https://peter-wyss.ch' # <-- MODIFY ME
# website title
title = 'Bridget' # <-- MODIFY ME
# don't touch this
disableKinds = ["section", "taxonomy", "term", "home"]
# robots.txt
enableRobotsTXT = true